name: Tests Coverage

on:
  push:
    branches: ["main"]


jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
    steps:
      - uses: actions/checkout@v2
      - name: Install Java Version
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
